Generate json for system methods
minecraft-addon-tools/minecraft-documentation-extractor pull request #3
Opened 2019-05-28 14:10 UTC by AtomicBlom

2019-05-29 22:26 UTC, abc-55 requested changes

2019-05-29 22:26 UTC, abc-55 commented on src/extractMethods.ts
> +            next();
This recursion is confusing. When `next()` returns, the condition is already false, so the `while` executes only once. The actual loop is created by recursion, not by `while`.

Change to `node = node.next();`

2019-05-29 22:26 UTC, abc-55 commented on src/index.ts
> +        var systemMethodCategories: {[key: string]: string} = {
Should be `const` (maybe i can configure tslint to check for things like that)

2019-05-29 22:26 UTC, abc-55 commented on src/index.ts
> +            const arrayTypeCheck = (returnType.type || "").toString().toLocaleLowerCase();
This should be just `toLowerCase`. `toLocaleLowerCase` might for example convert uppercase i to dotless i in Turkish locale.

2019-05-29 22:26 UTC, abc-55 commented on src/overrides.ts
>  export function applyOverridesToDocumentation(documentation: MinecraftScriptDocumentation) {
This needs a better name to distinguish it from the `applyOverrides` function below. Maybe `applyDefaultOverrides`?

2019-05-29 22:26 UTC, abc-55 commented on src/overrides.ts
> +        console.info(`actual  : ${JSON.stringify(overrideDefinitionVersion)}`);
expected should be `overrideDefinitionVersion`, actual should be `documentationVersion`

2019-05-30 01:18 UTC, AtomicBlom commented on src/extractMethods.ts
> +            next();
Good catch. That certainly wasn't my intention.

2019-05-30 01:21 UTC, AtomicBlom commented on src/index.ts
> +        var systemMethodCategories: {[key: string]: string} = {
Fixed.
We don't actually have tslint in the project, but I agree we really should, so I tried adding it but the 325 errors I got made me think that's a bit of a big change for this PR.
There's also a HEAP of warnings that I debate, such as enforced trailing commas, spaces between `<type> variable` when casting, and a 120 character line limit (I normally work to 160 nowadays)

2019-05-30 01:21 UTC, AtomicBlom commented on src/index.ts
> +            const arrayTypeCheck = (returnType.type || "").toString().toLocaleLowerCase();
ooh, I'm glad you picked up on that. I'm pretty bad with locale issues. Fixed.

2019-05-30 01:24 UTC, AtomicBlom commented
Hmm, looks like reviews on GitHub don't quite work the same as on Azure DevOps and it hides any comments that are left, so I'll resummarize here.

Good set of advice there. I've adopted all the ones mentioned.

We don't actually have tslint in the project, but I agree we really should, so I tried adding it but the 325 errors I got made me think that's a bit of a big change for this PR.
There's also a HEAP of warnings that I debate, such as enforced trailing commas, spaces between <type> variable when casting, and a 120 character line limit (I normally work to 160 nowadays)

2019-06-05 12:55 UTC, merged